### ISSUE TITLE
Sprint 2 - Requirements, Use Cases, and Diagrams

### ISSUE THREAD

**Issue by brand-ing** [brand-ing/study-group-finder#4]
Everyone for this sprint is expected to take **4 requirements, 4 use cases, and 1 diagram a piece**. The format for the use cases and stuff are in the document here: 

https://docs.google.com/document/d/1Np-vedkcQCFEEkJeb58YQvdN9jTqJ7OD0seFmVHuy4c/edit?usp=sharing

Here are the ideas we've come up with so far please reply with the ones you have selected or if you come up with some better ones that's cool too! We just don't want people taking the same ones. 

1. Login/ Registration Page
2. Group Dashboard
3. Profile Creation
4. Study Group search/filter
5. Quick polls
6. Task Manager
7. Public group discussion
8. Group Creation
9. File sharing
10. DMs
11. Tutoring Group Dependency
12. Notification system
13. Scheduling/ Calendar
14. Messaging
15. Support requests
17. User personal moderation
19. Friends & Contacts
21. User matchmaking
22. Group Management

Have a good weekend and remember this is due on Monday.

**Comment by CalvinJenks** [comment]
I'm going to work on 1-3 and 5. I already completed 1 and I'm going to try to finish all them before the end of Saturday!

**Comment by brand-ing** [comment]
quick polls
DMs
File Sharing
Public Group Discussion

**Comment by kamuluru1** [comment]
Tutoring Group Dependancy
Notification System
Scheduling
User Matchmaking

**Comment by jjketten** [comment]
14, 15, 16, 17 are complete.


~~1. Login/ Registration Page~~
2. Group Dashboard
~~3. Profile Creation~~
~~4. Study Group search/filter~~
~~5. Quick polls~~
~~6. Task Manager~~
~~7. Public group discussion~~
8. Group Creation
~~9. File sharing~~
~~10. DMs~~
~~11. Tutoring Group Dependency~~
~~12. Notification system~~
~~13. Scheduling/ Calendar~~
~~14. Messaging~~
~~15. Support requests~~
~~16. User personal moderation~~
~~17. Friends & Contacts~~
~~18. User matchmaking~~
19. Group Management
