### ISSUE TITLE
Sprint 3 | Remaining Tasks

### ISSUE THREAD

**Issue by jjketten** [brand-ing/study-group-finder#6]
- [x] **Section 7:** System-wide Class Diagram - mostly finished, just needs review and upload to google doc
- [x] **Section 8:** UML Sequence Diagram - 1/2 in google doc
- [ ] **Section 9:** Implementation: 
- [x]     A. Database setup & Communication Test #7 
- [x]     B. Database Table implementation
- [ ]     C. Major use case 1
- [ ]     D. Major use case 2
- [ ]     E. "A description of how to compile and run your code"

**Comment by jjketten** [comment]
Going to move remaining implementation tasks to Demo day "iteration"

**Comment by brand-ing** [comment]
Awesome I was thinking about doing that. Can you show me how to make an iteration later?
