### ISSUE TITLE
Sprint 3 | 9A. Database setup & Communication Test

### ISSUE THREAD

**Issue by jjketten** [brand-ing/study-group-finder#7]
- [x] Database creation
- [x] Basic dependency implementation & connection test with Springboot 
I'll be working on my setup-test branch for this. I might implement some CRUD functions

For simplicity I think we will just have one Cloud Firestore for now. Hypothetically, we may be able to get away with this as long as we don't have two or more branches changing the data model at the same time (famous last words)
If we need to have separate ones later for development purposes we can integrate the local emulator into the devcontainer (probably).

**Comment by jjketten** [comment]
- study-group-finder-833f3 database has been created & I added everyone's gmail accounts as Editors.
- I've implemented a way to use the dev container's environment variables to pass in the location secret key for the service account, which has also been added to .gitignore
- Also working on CRUD functions

**Comment by jjketten** [comment]
okay, nice
![image](https://github.com/user-attachments/assets/4069f992-f485-4f28-999d-785a3855568c)

**Comment by brand-ing** [comment]
Neat I am going to try to check this out and see if I can set it up
